name = "SymbolicWedderburn"
uuid = "858aa9a9-4c7c-4c62-b466-2421203962a2"
authors = ["Marek Kaluba <kalmar@amu.edu.pl>", "tweisser <tillmann.weisser@web.de>"]
version = "0.2.0"

[deps]
Cyclotomics = "da8f5974-afbb-4dc8-91d8-516d5257c83b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PermutationGroups = "8bc5a954-2dfc-11e9-10e6-cd969bffa420"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Cyclotomics = "0.2.0"
PermutationGroups = "0.2.1"
Primes = "0.4, 0.5"
julia = "1"
